#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

exchangerates:
    path: /api/get-exchange-rates
    controller: App\Controller\ExchangeRatesController::getRates

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

